# Generated by Django 3.2.9 on 2022-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select A Genre For This Book', to='catalog.Genre'),
        ),
    ]
